## Limpieza de Datos: Compras Públicas Municipalidades

Este notebook documenta el proceso de limpieza y estandarización de datos de compras públicas municipales en Chile, obtenidos de la plataforma Mercado Público. El objetivo es preparar los datasets para un EDA posterior.

Para correr este notebook es necesario tener un una carpeta llamada Municipalidad con los datos en formato csv, en el mismo directorio. el formato es:

"Limpieza/Municipalidades/CompraAgil.csv" 


Se trabajará con 4 datasest: 

*  Compra Ágil
* Convenio Marco
* Licitación
* Trato Directo


!! Por ahora no trabajare con Convenio Marco, más adelante verémos si es de utilidad

In [15]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
 
#sklearn
from sklearn.model_selection import KFold
from sklearn.preprocessing import RobustScaler

In [16]:
def clean_dataset(df, data_name):
    """
    Función para limpiar tipos de datos en datasets de compras públicas
    """

    # Fechas
    if 'FechaEnvioOC' in df.columns:
            df['FechaEnvioOC'] = pd.to_datetime(df['FechaEnvioOC'], dayfirst=True, errors='coerce')
    
    # Limpiar texto
    text_columns = ['Proveedor', 'Institucion', 'NombreOC', 'NombreItem']
    for col in text_columns:
        if col in df.columns:
            df[col] = df[col].astype(str).str.strip().str.upper()
    
    # Filtrar solo CLP en MonedaOC y luego eliminar la columna
    if 'MonedaOC' in df.columns:
        # Convertir a string y limpiar
        df['MonedaOC'] = df['MonedaOC'].astype(str).str.strip().str.upper()
        # Filtrar solo filas con CLP
        df = df[df['MonedaOC'] == 'CLP']
        # Eliminar la columna MonedaOC
        df = df.drop('MonedaOC', axis=1)
    
    #limpiar comas:
    for col in df.columns:
            df[col] = df[col].astype(str).str.replace(',', '.', regex=False)
            
            
    # Montos
    for col in [
                "MontoTotalItem",
                "CantidadItem",
                'CodigoProductoONU'
               ]:
            
        if col in df.columns:
            #arreglar formatos
            df[col] = df[col].astype(str).str.replace('.', '', regex=False)
            df[col] = df[col].str.replace(',', '.', regex=False)
            df[col] = pd.to_numeric(df[col], errors='coerce')
            
            # para trabajar con enteros
            df[col] = df[col].round().astype('Int64')
    
    #filtros de categorías
    nombres_interes = [
        "SERVICIOS DE AUTOBUSES CONTRATADOS",
        "ARTÍCULOS DE PAPELERÍA",
        "GALLETAS DULCES O PASTELITOS",
        "SERVICIOS DE SUMINISTRO DE ALIMENTOS",
        "PRODUCCIÓN DE EVENTOS",
        "TÓNER",
        "ARRIENDO DE VEHÍCULOS",
        "EXÁMENES MÉDICOS",
        "LÁPIZ PASTA",
        "TINTAS"
    ]
    if 'NombreItem' in df.columns:
        df = df[df['NombreItem'].isin(nombres_interes)]
    return df

In [17]:
def clean_missing_values(df):
    if "CantidadItem" in df.columns:
        # dropear la fila si la cantidad es 0 o nulo 
        df = df.dropna(subset=["CantidadItem"])
        df = df[df["CantidadItem"] != 0]
        
    if "MontoTotalItem" in df.columns:
        # dropear la fila si la cantidad es 0 o nulo 
        df = df.dropna(subset=["MontoTotalItem"])
        df = df[df["MontoTotalItem"] != 0]
     
    if "Institucion" in df.columns:
        # dropear si el dato es nulo
        df = df.dropna(subset=["Institucion"])
        
    return df

In [18]:
'''
Aqui voy a seleccionar algunas columnas de interés
'''

columns_to_keep = [
    "codigoOC",
    "NroLicitacion",
    "EstadoOC",
    "NombreOC",
     
    # Institución compradora
    "Institucion",
    "UnidadCompra",
    "RegionUnidadCompra",
    "Financiamiento",
    'Financiamiento',
    # Proveedor
    "Proveedor",
    'ActividadProveedor',
    'TamanoProveedor',
    
    # Montos y compra
    "MontoTotalItem",
    "MonedaOC",
    "MetodoPago",
    'TipoDespacho',
    
    # Producto / Servicio
    "NombreItem",
    "CantidadItem",
    "CodigoProductoONU"

]

In [19]:
'''
Limpieza básica de eliminación de nulos y duplicados
'''
df_li = pd.read_csv("Municipalidades/Licitacion.csv", sep=";", encoding="latin1", usecols=columns_to_keep)

df_li = df_li.drop_duplicates()

df_li = clean_missing_values(df_li)

df_li = clean_dataset(df_li, "Licitacion")

In [20]:
df_li.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28551 entries, 52 to 250821
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   codigoOC            28551 non-null  object
 1   NroLicitacion       28551 non-null  object
 2   NombreOC            28551 non-null  object
 3   EstadoOC            28551 non-null  object
 4   MetodoPago          28551 non-null  object
 5   TipoDespacho        28551 non-null  object
 6   Financiamiento      28551 non-null  object
 7   UnidadCompra        28551 non-null  object
 8   RegionUnidadCompra  28551 non-null  object
 9   Institucion         28551 non-null  object
 10  Proveedor           28551 non-null  object
 11  ActividadProveedor  28551 non-null  object
 12  TamanoProveedor     28551 non-null  object
 13  CodigoProductoONU   28551 non-null  Int64
 14  NombreItem          28551 non-null  object
 15  CantidadItem        28551 non-null  Int64
 16  MontoTotalItem      28551 non-null  Int64
dtypes: Int64(3), object(14)
memory usage: 4.0+ MB

In [21]:
# para los siguientes datasts, hay que sacar "NroLicitacion"
columns_to_keep_2 = columns_to_keep.copy()  
columns_to_keep_2.pop(1)

'NroLicitacion'

In [22]:
'''
Limpieza básica de eliminación de nulos y duplicados
'''
df_td = pd.read_csv("Municipalidades/TratoDirecto.csv", sep=";", encoding="latin1", usecols=columns_to_keep_2)
df_td = df_td.drop_duplicates()
df_td = clean_dataset(df_td, "TratoDirecto")
df_td = clean_missing_values(df_td)

In [23]:
df_td.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3297 entries, 2 to 43850
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   codigoOC            3297 non-null   object
 1   NombreOC            3297 non-null   object
 2   EstadoOC            3297 non-null   object
 3   MetodoPago          3297 non-null   object
 4   TipoDespacho        3297 non-null   object
 5   Financiamiento      3297 non-null   object
 6   UnidadCompra        3297 non-null   object
 7   RegionUnidadCompra  3297 non-null   object
 8   Institucion         3297 non-null   object
 9   Proveedor           3297 non-null   object
 10  ActividadProveedor  3297 non-null   object
 11  TamanoProveedor     3297 non-null   object
 12  CodigoProductoONU   3297 non-null   Int64
 13  NombreItem          3297 non-null   object
 14  CantidadItem        3297 non-null   Int64
 15  MontoTotalItem      3297 non-null   Int64
dtypes: Int64(3), object(13)
memory usage: 447.5+ KB

In [24]:
df_ca = pd.read_csv("Municipalidades/CompraAgil.csv", sep=";", encoding="latin1", usecols=columns_to_keep_2)
df_ca = df_ca.dropna(subset=["Proveedor", "CantidadItem"])
df_ca = df_ca.drop_duplicates()
df_ca = clean_dataset(df_ca, "CompraAgil")
df_ca = clean_missing_values(df_ca)

/var/folders/rn/8kg7t05x7l3fy1mwbgcdkw240000gp/T/ipykernel_50331/2859359492.py:1: DtypeWarning: Columns (35,42) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ca = pd.read_csv("Municipalidades/CompraAgil.csv", sep=";", encoding="latin1", usecols=columns_to_keep_2)

In [25]:
df_ca.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32639 entries, 236 to 2492913
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   codigoOC            32639 non-null  object
 1   NombreOC            32639 non-null  object
 2   EstadoOC            32639 non-null  object
 3   MetodoPago          32639 non-null  object
 4   TipoDespacho        32639 non-null  object
 5   Financiamiento      32639 non-null  object
 6   UnidadCompra        32639 non-null  object
 7   RegionUnidadCompra  32639 non-null  object
 8   Institucion         32639 non-null  object
 9   Proveedor           32639 non-null  object
 10  ActividadProveedor  32639 non-null  object
 11  TamanoProveedor     32639 non-null  object
 12  CodigoProductoONU   32639 non-null  Int64
 13  NombreItem          32639 non-null  object
 14  CantidadItem        32639 non-null  Int64
 15  MontoTotalItem      32639 non-null  Int64
dtypes: Int64(3), object(13)
memory usage: 4.3+ MB

In [26]:
# Concatenar datasets
df_li['TipoCompra'] = 'Licitacion'
df_td['TipoCompra'] = 'Trato Directo'
df_ca['TipoCompra'] = 'Compra Agil'

df_combined = pd.concat([df_li, df_td, df_ca], ignore_index=True)

df_combined['Precio_Unitario_TOTAL'] = df_combined['MontoTotalItem'] / df_combined['CantidadItem']
print(f"Dataset combinado: {df_combined.shape}")

# crear carpeta si no existe
output_dir = "../datos_limpios"
if not os.path.exists(output_dir):
    os.makedirs(output_dir)
  
# Guardar archivo
output_file = "../datos_limpios/municipalidades_combinado.csv"
df_combined.to_csv(output_file, index=False, encoding="utf-8")

Dataset combinado: (64487, 19)

In [27]:
df_combined

,codigoOC,NroLicitacion,NombreOC,EstadoOC,MetodoPago,TipoDespacho,Financiamiento,UnidadCompra,RegionUnidadCompra,Institucion,Proveedor,ActividadProveedor,TamanoProveedor,CodigoProductoONU,NombreItem,CantidadItem,MontoTotalItem,TipoCompra,Precio_Unitario_TOTAL
0,2992-331-SE25,2992-176-LQ24,CONVENIO DE LIBRERIA,Recepcion Conforme,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,215-22-04-002-001,I MUNICIPALIDAD DE MONTEPATRIA,Region de Coquimbo,I MUNICIPALIDAD DE MONTEPATRIA,INVERSIONES Y RENTAS AMINORTE LIMITADA,VENTA AL POR MAYOR DE ARTICULOS DE PAPELERIA Y...,Pequeña,14111509,ARTÍCULOS DE PAPELERÍA,14,19600,Licitacion,1400.0
1,4858-438-SE25,4858-41-LE25,CONTRATO SUMINISTRO ALIMENTOS E INSUMOS DE SUPER.,Enviada a Proveedor,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,2201001,Finanzas,Region del Biobio,I MUNICIPALIDAD DE TIRUA,COMERCIALIZADORA LOS PEREZ LIMITADA,comercializadora,Mediana,93131608,SERVICIOS DE SUMINISTRO DE ALIMENTOS,47,47000,Licitacion,1000.0
2,4858-438-SE25,4858-41-LE25,CONTRATO SUMINISTRO ALIMENTOS E INSUMOS DE SUPER.,Enviada a Proveedor,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,2201001,Finanzas,Region del Biobio,I MUNICIPALIDAD DE TIRUA,COMERCIALIZADORA LOS PEREZ LIMITADA,comercializadora,Mediana,93131608,SERVICIOS DE SUMINISTRO DE ALIMENTOS,18,27000,Licitacion,1500.0
3,4858-438-SE25,4858-41-LE25,CONTRATO SUMINISTRO ALIMENTOS E INSUMOS DE SUPER.,Enviada a Proveedor,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,2201001,Finanzas,Region del Biobio,I MUNICIPALIDAD DE TIRUA,COMERCIALIZADORA LOS PEREZ LIMITADA,comercializadora,Mediana,93131608,SERVICIOS DE SUMINISTRO DE ALIMENTOS,3,3000,Licitacion,1000.0
4,3928-343-SE25,3928-29-LE25,ADQUISICION DE PRODUCTOS DE ALIMENTOS PARA ES...,Recepcion Conforme,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,nan,Educación Municipal,Region del Libertador General Bernardo OHiggins,ILUSTRE MUNICIPALIDAD DE PICHILEMU,MANUEL BENJAMIN PADILLA RODRIGUEZ,CULTIVO DE TRIGO| CULTIVO FORRAJEROS EN PRADER...,Mediana,50181905,GALLETAS DULCES O PASTELITOS,5,3570,Licitacion,714.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64482,377-247-AG25,NaN,ORDEN DE COMPRA GENERADA POR INVITACIÓN A COMP...,Aceptada,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,nan,MUNICIPALIDAD DE ALGARROBO-ADQUISICIONES,Region de Valparaiso,I MUNICIPALIDAD DE ALGARROBO,IMPORTADORA Y EXPORTADORA VIS SPA,nan,Pequeña,50181905,GALLETAS DULCES O PASTELITOS,500,1000000,Compra Agil,2000.0
64483,4519-187-AG25,NaN,ADQUISICION DE MATERIALES DE OFICINA PARA TALL...,Aceptada,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,2140509,Administración y Finanzas,Region del Nuble,I MUNICIPALIDAD DE TREHUACO,LIBRERÍA ATLANTIK LIMITADA,ALMACENES PEQUENOS (VENTA DE ALIMENTOS)| COMER...,Mediana,12171703,TINTAS,2,62656,Compra Agil,31328.0
64484,3947-461-AG25,NaN,ARTICULOS DE LIBRERIA PARA EL PROGRAMA CONOZCA...,Aceptada,30 dias contra la recepcion conforme de la fac...,Otra Forma de Despacho,2140501036,Municipalidad de Santa Juana,Region del Biobio,I MUNICIPALIDAD DE SANTA JUANA,LIBRERÍA ATLANTIK LIMITADA,ALMACENES PEQUENOS (VENTA DE ALIMENTOS)| COMER...,Mediana,12171703,TINTAS,3,56625,Compra Agil,18875.0
64485,3882-198-AG25,NaN,INSUMOS PARA TALLERES- DIDECO 1045-1046,Recepcion Conforme,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,ADMINISTRACION DE FONDOS,Ilustre Municipalidad de Llay Llay,Region de Valparaiso,I MUNICIPALIDAD DE LLAY LLAY,KARINA PAIS LORCA,Karina Pais Lorca,NoClasificado,50181905,GALLETAS DULCES O PASTELITOS,4,13172,Compra Agil,3293.0
64486,3882-198-AG25,NaN,INSUMOS PARA TALLERES- DIDECO 1045-1046,Recepcion Conforme,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,ADMINISTRACION DE FONDOS,Ilustre Municipalidad de Llay Llay,Region de Valparaiso,I MUNICIPALIDAD DE LLAY LLAY,KARINA PAIS LORCA,Karina Pais Lorca,NoClasificado,50181905,GALLETAS DULCES O PASTELITOS,12,12360,Compra Agil,1030.0

### Quitar columnas que ya no usaremos

In [29]:
unspsc_data = pd.read_csv('../data/clean_unspsc_data.csv')
unspsc_data = unspsc_data[['Commodity Code', 'Commodity Name']]

In [30]:
data_merged = pd.merge(
    df_combined, 
    unspsc_data, 
    left_on='CodigoProductoONU', 
    right_on='Commodity Code', 
    how='left' 
)

data_merged = data_merged.drop(columns=['Commodity Code'])
# Ver las primeras filas para verificar
data_merged.head()

,codigoOC,NroLicitacion,NombreOC,EstadoOC,MetodoPago,TipoDespacho,Financiamiento,UnidadCompra,RegionUnidadCompra,Institucion,Proveedor,ActividadProveedor,TamanoProveedor,CodigoProductoONU,NombreItem,CantidadItem,MontoTotalItem,TipoCompra,Precio_Unitario_TOTAL,Commodity Name
0,2992-331-SE25,2992-176-LQ24,CONVENIO DE LIBRERIA,Recepcion Conforme,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,215-22-04-002-001,I MUNICIPALIDAD DE MONTEPATRIA,Region de Coquimbo,I MUNICIPALIDAD DE MONTEPATRIA,INVERSIONES Y RENTAS AMINORTE LIMITADA,VENTA AL POR MAYOR DE ARTICULOS DE PAPELERIA Y...,Pequeña,14111509,ARTÍCULOS DE PAPELERÍA,14,19600,Licitacion,1400.0,Stationery
1,4858-438-SE25,4858-41-LE25,CONTRATO SUMINISTRO ALIMENTOS E INSUMOS DE SUPER.,Enviada a Proveedor,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,2201001,Finanzas,Region del Biobio,I MUNICIPALIDAD DE TIRUA,COMERCIALIZADORA LOS PEREZ LIMITADA,comercializadora,Mediana,93131608,SERVICIOS DE SUMINISTRO DE ALIMENTOS,47,47000,Licitacion,1000.0,Food supply services
2,4858-438-SE25,4858-41-LE25,CONTRATO SUMINISTRO ALIMENTOS E INSUMOS DE SUPER.,Enviada a Proveedor,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,2201001,Finanzas,Region del Biobio,I MUNICIPALIDAD DE TIRUA,COMERCIALIZADORA LOS PEREZ LIMITADA,comercializadora,Mediana,93131608,SERVICIOS DE SUMINISTRO DE ALIMENTOS,18,27000,Licitacion,1500.0,Food supply services
3,4858-438-SE25,4858-41-LE25,CONTRATO SUMINISTRO ALIMENTOS E INSUMOS DE SUPER.,Enviada a Proveedor,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,2201001,Finanzas,Region del Biobio,I MUNICIPALIDAD DE TIRUA,COMERCIALIZADORA LOS PEREZ LIMITADA,comercializadora,Mediana,93131608,SERVICIOS DE SUMINISTRO DE ALIMENTOS,3,3000,Licitacion,1000.0,Food supply services
4,3928-343-SE25,3928-29-LE25,ADQUISICION DE PRODUCTOS DE ALIMENTOS PARA ES...,Recepcion Conforme,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,nan,Educación Municipal,Region del Libertador General Bernardo OHiggins,ILUSTRE MUNICIPALIDAD DE PICHILEMU,MANUEL BENJAMIN PADILLA RODRIGUEZ,CULTIVO DE TRIGO| CULTIVO FORRAJEROS EN PRADER...,Mediana,50181905,GALLETAS DULCES O PASTELITOS,5,3570,Licitacion,714.0,Sweet biscuits or cookies

### Clasificación de sobreprecio

In [31]:
# variables de control
MINIMO_TRANSACCIONES = 5
MINIMO_SOBREPRECIO_CLP_RELEVANTE = 10000
FACTOR_IQR = 2.0

#  Calcular límites y contadores 
p25_item = data_merged.groupby('Commodity Name')['Precio_Unitario_TOTAL'].transform('quantile', 0.25)
p75_item = data_merged.groupby('Commodity Name')['Precio_Unitario_TOTAL'].transform('quantile', 0.75)
iqr_item = p75_item - p25_item
n_transacciones = data_merged.groupby('Commodity Name')['Precio_Unitario_TOTAL'].transform('count')

# límite estadístico
limite_sobreprecio_stats = p75_item + (FACTOR_IQR * iqr_item)

# diferencia monetaria
diferencia_monetaria = data_merged['Precio_Unitario_TOTAL'] - p75_item

nombre_columna_cantidad = 'CantidadItem'  

data_merged['Monto_Total_Orden'] = data_merged['Precio_Unitario_TOTAL'] * data_merged[nombre_columna_cantidad]


# --- Etiquetar con todas las condiciones ---

#  Empezamos asumiendo (False)
data_merged['is_expensive'] = False

# Definimos las condiciones para un precio expensivo significativo
condicion_estadistica = (data_merged['Precio_Unitario_TOTAL'] > limite_sobreprecio_stats)
condicion_suficientes_datos = (n_transacciones >= MINIMO_TRANSACCIONES)
condicion_monetaria_relevante = (diferencia_monetaria >= MINIMO_SOBREPRECIO_CLP_RELEVANTE)

# El monto total de la línea debe ser > 200.000 y otro, lo voy a dejar en ese por ahora
condicion_monto_total_relevante = (data_merged['Monto_Total_Orden'] > 200000)


# Aplicamos la etiqueta 
data_merged.loc[
    condicion_estadistica & 
    condicion_suficientes_datos & 
    condicion_monetaria_relevante &
    condicion_monto_total_relevante,  
    'is_expensive'
] = True

# 3. Anulamos los que no tienen datos suficientes
condicion_insuficiente = (n_transacciones < MINIMO_TRANSACCIONES)
data_merged.loc[condicion_insuficiente, 'is_expensive'] = False

In [32]:
data_merged.head()

,codigoOC,NroLicitacion,NombreOC,EstadoOC,MetodoPago,TipoDespacho,Financiamiento,UnidadCompra,RegionUnidadCompra,Institucion,...,TamanoProveedor,CodigoProductoONU,NombreItem,CantidadItem,MontoTotalItem,TipoCompra,Precio_Unitario_TOTAL,Commodity Name,Monto_Total_Orden,is_expensive
0,2992-331-SE25,2992-176-LQ24,CONVENIO DE LIBRERIA,Recepcion Conforme,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,215-22-04-002-001,I MUNICIPALIDAD DE MONTEPATRIA,Region de Coquimbo,I MUNICIPALIDAD DE MONTEPATRIA,...,Pequeña,14111509,ARTÍCULOS DE PAPELERÍA,14,19600,Licitacion,1400.0,Stationery,19600.0,False
1,4858-438-SE25,4858-41-LE25,CONTRATO SUMINISTRO ALIMENTOS E INSUMOS DE SUPER.,Enviada a Proveedor,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,2201001,Finanzas,Region del Biobio,I MUNICIPALIDAD DE TIRUA,...,Mediana,93131608,SERVICIOS DE SUMINISTRO DE ALIMENTOS,47,47000,Licitacion,1000.0,Food supply services,47000.0,False
2,4858-438-SE25,4858-41-LE25,CONTRATO SUMINISTRO ALIMENTOS E INSUMOS DE SUPER.,Enviada a Proveedor,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,2201001,Finanzas,Region del Biobio,I MUNICIPALIDAD DE TIRUA,...,Mediana,93131608,SERVICIOS DE SUMINISTRO DE ALIMENTOS,18,27000,Licitacion,1500.0,Food supply services,27000.0,False
3,4858-438-SE25,4858-41-LE25,CONTRATO SUMINISTRO ALIMENTOS E INSUMOS DE SUPER.,Enviada a Proveedor,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,2201001,Finanzas,Region del Biobio,I MUNICIPALIDAD DE TIRUA,...,Mediana,93131608,SERVICIOS DE SUMINISTRO DE ALIMENTOS,3,3000,Licitacion,1000.0,Food supply services,3000.0,False
4,3928-343-SE25,3928-29-LE25,ADQUISICION DE PRODUCTOS DE ALIMENTOS PARA ES...,Recepcion Conforme,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,nan,Educación Municipal,Region del Libertador General Bernardo OHiggins,ILUSTRE MUNICIPALIDAD DE PICHILEMU,...,Mediana,50181905,GALLETAS DULCES O PASTELITOS,5,3570,Licitacion,714.0,Sweet biscuits or cookies,3570.0,False

In [33]:
# dropear lo que no nos sirve
df_model = data_merged.drop(columns=['codigoOC', 'Precio_Unitario_TOTAL', 'MontoTotalItem','NroLicitacion', 'NombreOC', 'ActividadProveedor','Financiamiento', 'CodigoProductoONU','UnidadCompra', 'NombreItem'])

In [34]:
df_model.head()

,EstadoOC,MetodoPago,TipoDespacho,RegionUnidadCompra,Institucion,Proveedor,TamanoProveedor,CantidadItem,TipoCompra,Commodity Name,Monto_Total_Orden,is_expensive
0,Recepcion Conforme,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,Region de Coquimbo,I MUNICIPALIDAD DE MONTEPATRIA,INVERSIONES Y RENTAS AMINORTE LIMITADA,Pequeña,14,Licitacion,Stationery,19600.0,False
1,Enviada a Proveedor,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,Region del Biobio,I MUNICIPALIDAD DE TIRUA,COMERCIALIZADORA LOS PEREZ LIMITADA,Mediana,47,Licitacion,Food supply services,47000.0,False
2,Enviada a Proveedor,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,Region del Biobio,I MUNICIPALIDAD DE TIRUA,COMERCIALIZADORA LOS PEREZ LIMITADA,Mediana,18,Licitacion,Food supply services,27000.0,False
3,Enviada a Proveedor,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,Region del Biobio,I MUNICIPALIDAD DE TIRUA,COMERCIALIZADORA LOS PEREZ LIMITADA,Mediana,3,Licitacion,Food supply services,3000.0,False
4,Recepcion Conforme,30 dias contra la recepcion conforme de la fac...,Despachar a Dirección de envío,Region del Libertador General Bernardo OHiggins,ILUSTRE MUNICIPALIDAD DE PICHILEMU,MANUEL BENJAMIN PADILLA RODRIGUEZ,Mediana,5,Licitacion,Sweet biscuits or cookies,3570.0,False

In [35]:
df_model.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64487 entries, 0 to 64486
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   EstadoOC            64487 non-null  object
 1   MetodoPago          64487 non-null  object
 2   TipoDespacho        64487 non-null  object
 3   RegionUnidadCompra  64487 non-null  object
 4   Institucion         64487 non-null  object
 5   Proveedor           64487 non-null  object
 6   TamanoProveedor     64487 non-null  object
 7   CantidadItem        64487 non-null  Int64
 8   TipoCompra          64487 non-null  object
 9   Commodity Name      64487 non-null  object
 10  Monto_Total_Orden   64487 non-null  Float64
 11  is_expensive        64487 non-null  bool
dtypes: Float64(1), Int64(1), bool(1), object(9)
memory usage: 5.6+ MB

### Estandarización y normalización

### 1.1.2 Encode the Categorical Data

In [36]:
df_model = pd.get_dummies(
    df_model,
    columns=['EstadoOC', 'TipoDespacho', 'TipoCompra', 'RegionUnidadCompra', 'TamanoProveedor', 'Commodity Name', 'MetodoPago'],
    drop_first=True
)

### 1.2.2 Encodeed k-fold

In [37]:
# K-Fold target encoding on 'Financiamiento', 'UnidadCompra', 'Institucion', 'Proveedor', 'RegionProveedor', 'NombreItem' columns
def kfold_target_encoding(data, column, target, n_splits=6):
    kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)
    encoded_column = pd.Series(index=data.index, dtype=float)

    for train_index, val_index in kf.split(data):
        train_data, val_data = data.iloc[train_index], data.iloc[val_index]
        means = train_data.groupby(column)[target].mean()
        encoded_column.iloc[val_index] = val_data[column].map(means)

    return encoded_column

for col in ['Proveedor', 'Institucion']:
    df_model[f'{col}_encoded'] = kfold_target_encoding(df_model, col, 'is_expensive')
    
df_model = df_model.drop(columns=['Proveedor', 'Institucion'])

In [38]:
df_model.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64487 entries, 0 to 64486
Data columns (total 49 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   CantidadItem                                                        64487 non-null  Int64
 1   Monto_Total_Orden                                                   64487 non-null  Float64
 2   is_expensive                                                        64487 non-null  bool
 3   EstadoOC_En Proceso                                                 64487 non-null  bool
 4   EstadoOC_Enviada a Proveedor                                        64487 non-null  bool
 5   EstadoOC_Recepcion Conforme                                         64487 non-null  bool
 6   EstadoOC_Solicitud de Cancelacion                                   64487 non-null  bool
 7   TipoDespacho_Despachar a Dirección de envío                         64487 non-null  bool
 8   TipoDespacho_Despachar según programa adjuntado                     64487 non-null  bool
 9   TipoDespacho_Despacho por courier o encomienda terrestre            64487 non-null  bool
 10  TipoDespacho_Otra Forma de Despacho                                 64487 non-null  bool
 11  TipoDespacho_Otra Forma de Despacho. Ver Instruc                    64487 non-null  bool
 12  TipoDespacho_Retiramos de su bodega                                 64487 non-null  bool
 13  TipoCompra_Licitacion                                               64487 non-null  bool
 14  TipoCompra_Trato Directo                                            64487 non-null  bool
 15  RegionUnidadCompra_Region Metropolitana de Santiago                 64487 non-null  bool
 16  RegionUnidadCompra_Region de Antofagasta                            64487 non-null  bool
 17  RegionUnidadCompra_Region de Arica y Parinacota                     64487 non-null  bool
 18  RegionUnidadCompra_Region de Atacama                                64487 non-null  bool
 19  RegionUnidadCompra_Region de Coquimbo                               64487 non-null  bool
 20  RegionUnidadCompra_Region de Los Rios                               64487 non-null  bool
 21  RegionUnidadCompra_Region de Magallanes y de la Antartica           64487 non-null  bool
 22  RegionUnidadCompra_Region de Tarapaca                               64487 non-null  bool
 23  RegionUnidadCompra_Region de Valparaiso                             64487 non-null  bool
 24  RegionUnidadCompra_Region de la Araucania                           64487 non-null  bool
 25  RegionUnidadCompra_Region de los Lagos                              64487 non-null  bool
 26  RegionUnidadCompra_Region del Biobio                                64487 non-null  bool
 27  RegionUnidadCompra_Region del Libertador General Bernardo OHiggins  64487 non-null  bool
 28  RegionUnidadCompra_Region del Maule                                 64487 non-null  bool
 29  RegionUnidadCompra_Region del Nuble                                 64487 non-null  bool
 30  RegionUnidadCompra_nan                                              64487 non-null  bool
 31  TamanoProveedor_Mediana                                             64487 non-null  bool
 32  TamanoProveedor_Micro                                               64487 non-null  bool
 33  TamanoProveedor_NoClasificado                                       64487 non-null  bool
 34  TamanoProveedor_Pequeña                                             64487 non-null  bool
 35  Commodity Name_Chartered bus services                               64487 non-null  bool
 36  Commodity Name_Events management                                    64487 non-null  bool
 37  Commodity Name_Food supply services                                 64487 non-null  bool
 38  Commodity Name_Individual health assessment                         64487 non-null  bool
 39  Commodity Name_Inks                                                 64487 non-null  bool
 40  Commodity Name_Printer or facsimile toner                           64487 non-null  bool
 41  Commodity Name_Rollerball pens                                      64487 non-null  bool
 42  Commodity Name_Stationery                                           64487 non-null  bool
 43  Commodity Name_Sweet biscuits or cookies                            64487 non-null  bool
 44  Commodity Name_Vehicle rental                                       64487 non-null  bool
 45  MetodoPago_A 45 dias                                                64487 non-null  bool
 46  MetodoPago_Otro. Ver Instrucciones                                  64487 non-null  bool
 47  Proveedor_encoded                                                   61785 non-null  float64
 48  Institucion_encoded                                                 64486 non-null  float64
dtypes: Float64(1), Int64(1), bool(45), float64(2)
memory usage: 4.9 MB

In [39]:
df_model.to_csv('../Data_numerical.csv', index=False, encoding='utf-8')

## Separación para modelos no supervisados

In [40]:
# dropear lo que no nos sirve
df_model_ns = data_merged.drop(columns=['codigoOC', 'NroLicitacion', 'NombreOC', 'Financiamiento', 'CodigoProductoONU','UnidadCompra', 'RegionUnidadCompra','NombreItem'])

In [41]:
df_model_ns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64487 entries, 0 to 64486
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   EstadoOC               64487 non-null  object
 1   MetodoPago             64487 non-null  object
 2   TipoDespacho           64487 non-null  object
 3   Institucion            64487 non-null  object
 4   Proveedor              64487 non-null  object
 5   ActividadProveedor     64487 non-null  object
 6   TamanoProveedor        64487 non-null  object
 7   CantidadItem           64487 non-null  Int64
 8   MontoTotalItem         64487 non-null  Int64
 9   TipoCompra             64487 non-null  object
 10  Precio_Unitario_TOTAL  64487 non-null  Float64
 11  Commodity Name         64487 non-null  object
 12  Monto_Total_Orden      64487 non-null  Float64
 13  is_expensive           64487 non-null  bool
dtypes: Float64(2), Int64(2), bool(1), object(9)
memory usage: 6.7+ MB

In [42]:
df_model_ns = pd.get_dummies(
    df_model_ns,
    columns=['EstadoOC', 'TipoDespacho', 'TipoCompra', 'TamanoProveedor', 'Commodity Name', 'MetodoPago'],
    drop_first=True
)

In [43]:
df_model_ns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64487 entries, 0 to 64486
Data columns (total 36 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   Institucion                                               64487 non-null  object
 1   Proveedor                                                 64487 non-null  object
 2   ActividadProveedor                                        64487 non-null  object
 3   CantidadItem                                              64487 non-null  Int64
 4   MontoTotalItem                                            64487 non-null  Int64
 5   Precio_Unitario_TOTAL                                     64487 non-null  Float64
 6   Monto_Total_Orden                                         64487 non-null  Float64
 7   is_expensive                                              64487 non-null  bool
 8   EstadoOC_En Proceso                                       64487 non-null  bool
 9   EstadoOC_Enviada a Proveedor                              64487 non-null  bool
 10  EstadoOC_Recepcion Conforme                               64487 non-null  bool
 11  EstadoOC_Solicitud de Cancelacion                         64487 non-null  bool
 12  TipoDespacho_Despachar a Dirección de envío               64487 non-null  bool
 13  TipoDespacho_Despachar según programa adjuntado           64487 non-null  bool
 14  TipoDespacho_Despacho por courier o encomienda terrestre  64487 non-null  bool
 15  TipoDespacho_Otra Forma de Despacho                       64487 non-null  bool
 16  TipoDespacho_Otra Forma de Despacho. Ver Instruc          64487 non-null  bool
 17  TipoDespacho_Retiramos de su bodega                       64487 non-null  bool
 18  TipoCompra_Licitacion                                     64487 non-null  bool
 19  TipoCompra_Trato Directo                                  64487 non-null  bool
 20  TamanoProveedor_Mediana                                   64487 non-null  bool
 21  TamanoProveedor_Micro                                     64487 non-null  bool
 22  TamanoProveedor_NoClasificado                             64487 non-null  bool
 23  TamanoProveedor_Pequeña                                   64487 non-null  bool
 24  Commodity Name_Chartered bus services                     64487 non-null  bool
 25  Commodity Name_Events management                          64487 non-null  bool
 26  Commodity Name_Food supply services                       64487 non-null  bool
 27  Commodity Name_Individual health assessment               64487 non-null  bool
 28  Commodity Name_Inks                                       64487 non-null  bool
 29  Commodity Name_Printer or facsimile toner                 64487 non-null  bool
 30  Commodity Name_Rollerball pens                            64487 non-null  bool
 31  Commodity Name_Stationery                                 64487 non-null  bool
 32  Commodity Name_Sweet biscuits or cookies                  64487 non-null  bool
 33  Commodity Name_Vehicle rental                             64487 non-null  bool
 34  MetodoPago_A 45 dias                                      64487 non-null  bool
 35  MetodoPago_Otro. Ver Instrucciones                        64487 non-null  bool
dtypes: Float64(2), Int64(2), bool(29), object(3)
memory usage: 5.5+ MB

In [44]:
def preparar_freq_encoding_para_csv(df, columnas):
    """
    Args:
        df (pd.DataFrame): DataFrame original.
        columnas (list): Lista de columnas a transformar.
        
    Returns:
        pd.DataFrame: Copia del DF con columnas '_freq' (enteros).
    """
    df_out = df.copy()
    
    for col in columnas:
        # 1. Contar frecuencia (rellenando nulos como rarezas = 1)
        frecuencias = df_out[col].value_counts()
        nombre_col_freq = f'{col}_freq'
        
        # Mapeamos el conteo real (Ej: 50, 1, 10000)
        df_out[nombre_col_freq] = df_out[col].map(frecuencias).fillna(1)
        
        # 2. Eliminar columna original de texto
        df_out = df_out.drop(columns=[col])

    return df_out

In [45]:
# 1. Definir columnas
cols_para_freq = ['Proveedor', 'Institucion', 'ActividadProveedor']

# 2. Aplicar la transformación (Ahora obtendrás números reales, ej: 5.4, 1.2, etc.)
X_anomalias_listo = preparar_freq_encoding_para_csv(df_model_ns, cols_para_freq)

# 3. Verificar que todo sea numérico (o booleano si ya hiciste dummies)
print(X_anomalias_listo.dtypes)

# 4. Guardar a CSV para tu siguiente etapa
# index=False para no ensuciar el archivo
X_anomalias_listo.to_csv('../datos_preparados_anomalias.csv', index=False)

CantidadItem                                                  Int64
MontoTotalItem                                                Int64
Precio_Unitario_TOTAL                                       Float64
Monto_Total_Orden                                           Float64
is_expensive                                                   bool
EstadoOC_En Proceso                                            bool
EstadoOC_Enviada a Proveedor                                   bool
EstadoOC_Recepcion Conforme                                    bool
EstadoOC_Solicitud de Cancelacion                              bool
TipoDespacho_Despachar a Dirección de envío                    bool
TipoDespacho_Despachar según programa adjuntado                bool
TipoDespacho_Despacho por courier o encomienda terrestre       bool
TipoDespacho_Otra Forma de Despacho                            bool
TipoDespacho_Otra Forma de Despacho. Ver Instruc               bool
TipoDespacho_Retiramos de su bodega                            bool
TipoCompra_Licitacion                                          bool
TipoCompra_Trato Directo                                       bool
TamanoProveedor_Mediana                                        bool
TamanoProveedor_Micro                                          bool
TamanoProveedor_NoClasificado                                  bool
TamanoProveedor_Pequeña                                        bool
Commodity Name_Chartered bus services                          bool
Commodity Name_Events management                               bool
Commodity Name_Food supply services                            bool
Commodity Name_Individual health assessment                    bool
Commodity Name_Inks                                            bool
Commodity Name_Printer or facsimile toner                      bool
Commodity Name_Rollerball pens                                 bool
Commodity Name_Stationery                                      bool
Commodity Name_Sweet biscuits or cookies                       bool
Commodity Name_Vehicle rental                                  bool
MetodoPago_A 45 dias                                           bool
MetodoPago_Otro. Ver Instrucciones                             bool
Proveedor_freq                                                int64
Institucion_freq                                              int64
ActividadProveedor_freq                                       int64
dtype: object